#@follow_tag(registry.redhat.io/ubi8/ruby-27:latest)
FROM registry.redhat.io/ubi8/ruby-27:1-73 AS builder

ENV REMOTE_SOURCES=${REMOTE_SOURCES:-"."}
ENV REMOTE_SOURCES_DIR=${REMOTE_SOURCES_DIR:-"."}

USER 0
RUN : 'removed yum-config-manager' \
 &&   BUILD_PKGS="make gcc-c++ libffi-devel autoconf automake libtool m4 redhat-rpm-config" \
 &&   RUNTIME_PKGS="hostname bc iproute" \
 &&   yum install -y --setopt=tsflags=nodocs $BUILD_PKGS $RUNTIME_PKGS \
 &&   rpm -V $BUILD_PKGS \
 &&   rpm -V $RUNTIME_PKGS \
 &&   yum clean all

## EXCLUDE BEGIN ##
ENV upstream_code=$REMOTE_SOURCES/fluentd/app/fluentd
## EXCLUDE END ##

ENV upstream_code=${upstream_code:-"."} \
    HOME=/opt/app-root/src 
COPY ${upstream_code}/jemalloc/ /tmp/jemalloc/
RUN pushd /tmp/jemalloc && \
        EXTRA_CFLAGS="$( rpm --eval '%{optflags}' )" ./autogen.sh && \
        make install_lib_shared install_bin && \
        cp COPYING /tmp/COPYING.jemalloc && \
    popd

COPY ${upstream_code}/source.jemalloc /source.jemalloc
RUN bash -c '. /source.jemalloc; echo jemalloc $JEMALLOC_VER >> /contents'

COPY ${upstream_code}/vendored_gem_src/ ${HOME}/vendored_gem_src/
COPY ${upstream_code}/lib ${HOME}/vendored_gem_src
COPY ${upstream_code}/install-gems.sh ${HOME}/vendored_gem_src/
COPY ${upstream_code}/*.patch.sh ${HOME}/vendored_gem_src/
COPY ${upstream_code}/*.patch ${HOME}/vendored_gem_src/

RUN cd ${HOME}/vendored_gem_src/ && ./install-gems.sh

#@follow_tag(registry.redhat.io/ubi8/ruby-27:latest)
FROM registry.redhat.io/ubi8/ruby-27:1-73 AS runtime

ENV REMOTE_SOURCES=${REMOTE_SOURCES:-"."}
## EXCLUDE BEGIN ##
ARG upstream_code=$REMOTE_SOURCES/fluentd/app/fluentd
## EXCLUDE END ##
ENV upstream_code=${upstream_code:-"."}

ENV BUILD_VERSION=1.14.6
ENV OS_GIT_MAJOR=1
ENV OS_GIT_MINOR=14
ENV OS_GIT_PATCH=6
ENV SOURCE_GIT_COMMIT=${CI_LOGGING_FLUENTD_UPSTREAM_COMMIT:-}
ENV SOURCE_GIT_URL=${CI_LOGGING_FLUENTD_UPSTREAM_URL:-}

ARG DATA_VERSION_VALUE=1.6.0
ARG FLUENTD_VERSION_VALUE=1.14.6
ARG CONTAINER_VALUE=oci

ENV DATA_VERSION=$DATA_VERSION_VALUE \
    FLUENTD_VERSION=$FLUENTD_VERSION_VALUE \
    HOME=/opt/app-root/src \
    PATH=/opt/app-root/src/bin:/opt/app-root/bin:$PATH \
    container=$CONTAINER_VALUE

USER 0
RUN RUNTIME_PKGS="hostname bc iproute" \
 &&   yum install -y --setopt=tsflags=nodocs $RUNTIME_PKGS \
 &&   rpm -V $RUNTIME_PKGS \
 &&   yum clean all

RUN mkdir -p /etc/fluent/plugin

COPY --from=builder /usr/local/lib/libjemalloc* /usr/local/lib
COPY --from=builder /usr/local/bin/fluentd /usr/local/bin
COPY --from=builder /usr/local/bin/fluent-cat /usr/local/bin
COPY --from=builder /usr/local/bin/jemalloc-config /usr/local/bin
COPY --from=builder /usr/local/bin/jemalloc.sh /usr/local/bin
COPY --from=builder /usr/local/bin/jeprof /usr/local/bin

COPY --from=builder /usr/local/share/gems /usr/local/share/gems
COPY --from=builder /usr/local/lib64/gems/ruby /usr/local/lib64/gems/ruby
COPY ${upstream_code}/out_syslog_buffered.rb /etc/fluent/plugin/
COPY ${upstream_code}/out_syslog.rb /etc/fluent/plugin/
COPY ${upstream_code}/out_rawtcp.rb /etc/fluent/plugin/
COPY ${upstream_code}/run.sh ${HOME}/
COPY ${upstream_code}/generate_syslog_config.rb ${HOME}/
COPY ${upstream_code}/wait_for_es_version.rb ${HOME}/
COPY ${upstream_code}/wait_for_es_version.sh ${HOME}/
COPY ${upstream_code}/utils/ /usr/local/bin/

RUN mkdir -p /etc/fluent/configs.d/user && \
    chmod 777 /etc/fluent/configs.d/user && \
    ln -s /etc/fluent/configs.d/user/fluent.conf /etc/fluent/fluent.conf

WORKDIR ${HOME}
CMD ["sh", "run.sh"]

LABEL \
        io.k8s.description="Fluentd container for collecting of container logs" \
        io.k8s.display-name="Fluentd" \
        io.openshift.tags="logging,collection,fluentd" \
        License="Apache-2.0" \
        vendor="Red Hat" \
        name="openshift-logging/fluentd-rhel8" \
        com.redhat.component="logging-fluentd-container" \
        io.openshift.maintainer.product="OpenShift Container Platform" \
        io.openshift.build.commit.id=${CI_LOGGING_FLUENTD_UPSTREAM_COMMIT} \
        io.openshift.build.source-location=${CI_LOGGING_FLUENTD_UPSTREAM_URL} \
        io.openshift.build.commit.url=${CI_LOGGING_FLUENTD_UPSTREAM_URL}/commit/${CI_LOGGING_FLUENTD_UPSTREAM_COMMIT} \
        version=v1.14.6

