source "https://rubygems.org"
gem 'fluentd', '1.16.2'
gem 'elasticsearch', '< 8.0'
gem 'fluent-plugin-kubernetes_metadata_filter', '3.2.0'
gem 'fluent-plugin-cloudwatch-logs', "0.14.2"
gem 'fluent-plugin-concat'
gem 'fluent-plugin-detect-exceptions', "0.0.14"
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-kafka', "0.19.0"
gem 'fluent-plugin-grafana-loki'
gem 'fluent-plugin-multi-format-parser'
gem 'fluent-plugin-record-modifier'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-systemd'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-splunk-hec', '1.3.2'
gem 'fluent-plugin-label-router'
gem 'libxml-ruby' #aws-sdk-core
gem 'typhoeus' # gems that supports elasticsearch
gem 'webrick',  '1.8.2'

# gems that support fluentd
gem 'oj'
gem 'bigdecimal'
gem 'openssl', '3.2.0' #LOG-3933

gem 'rake'

path 'lib' do
  gem 'filter_parse_json_field'
  gem 'filter_elasticsearch_genid_ext'
  gem 'fluent-plugin-viaq_data_model', "0.0.23"
  gem 'fluent-plugin-collected'
  gem 'fluent-plugin-remote-syslog'
  gem 'fluent-plugin-remote_syslog' 
  gem 'formatter-single-json-value'
  gem 'parser_viaq_host_audit'
  gem 'remote_syslog_sender'
  gem 'syslog_protocol'
end 
