source "https://rubygems.org"
gem 'fluentd', ENV['FLUENTD_VERSION'], :source=>"https://rubygems.org"
gem 'elasticsearch', '< 8.0'
gem 'fluent-plugin-kubernetes_metadata_filter', '3.0.1'
gem 'fluent-plugin-cloudwatch-logs', "0.14.2"
gem 'fluent-plugin-concat'
gem 'fluent-plugin-detect-exceptions', "0.0.14"
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-grafana-loki'
gem 'fluent-plugin-multi-format-parser'
gem 'fluent-plugin-record-modifier'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-systemd'
gem 'fluent-plugin-remote-syslog'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-splunk-hec'
gem 'fluent-plugin-label-router'
gem 'kubeclient'
gem 'typhoeus'
gem 'oj'
gem 'bigdecimal'

#Below gem(and two of its dependencies) are moved to O_A_L/fluentd/lib, but its dependencies still exist in O_A_L/fluentd/vendored_gem_src/
#gem 'fluent-plugin-remote_syslog', '1.0.0'

gem 'ffi'
gem 'uuidtools'
gem 'rake'
gem 'async'
gem 'async-http'
