FROM registry.ci.openshift.org/ocp/builder:ubi8.ruby.25

ENV FLUENTD_VERSION=1.14.5 \
    WORKDIR=/tmp/fluentd/lib

USER 0

ENV GEM_HOME=/tmp/vendor
RUN gem install rake:13.0.6 bundler:2.2.33 --no-ri --no-doc
WORKDIR ${WORKDIR}
COPY run-unit-tests.sh /tmp/
ENTRYPOINT /tmp/run-unit-tests.sh
COPY fluentd/lib ${WORKDIR}
RUN for d in $(ls $WORKDIR) ; do \
    pushd ${d} ; \
        bundle install ; \
    popd ; \
    done
RUN /tmp/run-unit-tests.sh
