FROM registry.access.redhat.com/ubi9/ruby-31

ENV FLUENTD_VERSION=1.14.6 \
    WORKDIR=/tmp/fluentd/lib

USER 0

ENV GEM_HOME=/tmp/vendor
RUN gem install rake:13.0.6
WORKDIR ${WORKDIR}
COPY run-unit-tests.sh /tmp/
ENTRYPOINT /tmp/run-unit-tests.sh
COPY fluentd/lib ${WORKDIR}
RUN for d in $(ls $WORKDIR) ; do \
    pushd ${d} ; \
        bundle install ; \ 
        rc=$?; if [ "$rc" != "0" ] ; then exit 1 ; fi ; \  
    popd ; \
    done
RUN /tmp/run-unit-tests.sh
